#start time
strt<-Sys.time()
#source("ph_load_raw_data.R")
source("ph_filter_cell_density.R")
source("ph_filter_extreme_missegmentataion.R")
source("ph_filter_in_mahalanobis.R")
source("ph_find_reproducible_repeats.R")
source("ph_scale_data.R")
source("ph_creating ground trugh data set.R")
source("ph_creating ground trugh data set feature edition.R")
source("ph_groundtruth_scaling and joining data.R")
#source("ph_find_set of features to use for clustering.R")
print(Sys.time()-strt)