#start time
strt<-Sys.time()
#source("ph_load_raw_data.R")
source("ph_filter_cell_density.R")
source("ph_filter_extreme_missegmentataion.R")
source("ph_filter_in_mahalanobis.R")
source("ph_find_reproducible_repeats.R")
source("ph_scale_data.R")
source("ph_create_ground_truth_data_set.R")
source("ph_create_ground_truth_feature.R")
source("ph_groundtruth_scaling_and_joining_data.R")
source("ph_find_set_of_features_to_use_for_clustering.R")##can take a lot of hours, better load previous res
source("ph_groud_truth_pca.R")
source("ph_find_optimal_clustering_technique.R")
print(Sys.time()-strt)